[package]
name = "hello-actix"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-session = { version = "0.11.0", features = ["cookie-session", "redis-session", "redis-session-native-tls", "redis-pool"] }
actix-web = "4"
