# fly.toml app configuration file generated for hello-actix on 2025-12-25T14:49:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app            = 'hello-actix'
primary_region = 'ams'

[build]

[env]
PORT = '8080'

[http_service]
auto_start_machines  = true
auto_stop_machines   = 'stop'
force_https          = true
internal_port        = 8080
min_machines_running = 0
processes            = ['app']

[[vm]]
cpu_kind  = 'shared'
cpus      = 1
memory    = '1gb'
memory_mb = 1024
